server:
  port: 8889

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: boss-bes-basedata-center
  datasource:
    url: jdbc:mysql://localhost:3306/boss?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 12345
    jedis:
      pool:
        ##连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        ##连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        ##连接池中的最大空闲连接
        max-idle: 8
        ##连接池中的最小空闲连接
        min-idle: 8
    ##连接超时时间（毫秒）
    timeout: 1200


mybatis:
  type-aliases-package: com.bosssoft.hr.train.pojo.entity
  mapper-locations: classpath:com.bosssoft.hr.train.dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

mapper:
  mappers: com.bosssoft.hr.train.dao.DictionaryDao
  identity: mysql

